version: '3.5'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    container_name: what-the-watch_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: andy
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - what-the-watch_data:/data/db

  mongodb-express:
    image: mongo-express:latest
    restart: always
    container_name: what-the-watch_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: andy
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://andy:password123@mongodb:27017/

volumes:
  what-the-watch_data:
